# English translations for pypowervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the pypowervm project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.1.11.dev47\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-10-02 09:44-0400\n"
"PO-Revision-Date: 2018-10-02 11:01-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=n != 1;"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: pypowervm/adapter.py:122
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "Protocollo non valido \"%s\""

#: pypowervm/adapter.py:128
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "Comunicazioni non codificate con PowerVM! Invertire la configurazione su https."

#: pypowervm/adapter.py:142
msgid "Calculating default audit memento failed, using 'default'."
msgstr "Calcolo memo di controllo predefinito non riuscito, si utilizza 'default'."

#: pypowervm/adapter.py:183
msgid "Local authentication not supported on HMC."
msgstr "Autenticazione locale non supportata sulla HMC."

#: pypowervm/adapter.py:202
#, python-format
msgid "Setting up event listener for %s"
msgstr "Impostazione del listener di eventi per %s"

#: pypowervm/adapter.py:272
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "Richiesta imprevista di gestione file su %s"

#: pypowervm/adapter.py:316
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "Errore imprevisto per %(meth)s %(url)s"

#: pypowervm/adapter.py:318
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "Errore imprevisto %(class)s per %(method)s %(url)s: %(excp)s"

#: pypowervm/adapter.py:355
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer "
"be used."
msgstr ""
"Un nuovo login è stato ritenuto non sicuro. Questa istanza di sessione non dovrebbe più "
"essere utilizzata."

#: pypowervm/adapter.py:363
#, python-format
msgid "Attempting re-login %s"
msgstr "Tentativo di nuovo login %s"

#: pypowervm/adapter.py:374
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"Nuovo login 401, corpo risposta:\n"
"%s"

#: pypowervm/adapter.py:379
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"Nuovo login non riuscito, corpo risposta:\n"
"%s"

#: pypowervm/adapter.py:383
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"Nuovo login non riuscito:\n"
"%s"

#: pypowervm/adapter.py:401
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"Nuovo tentativo non riuscito con un altro 401, corpo risposta:\n"
"%s"

#: pypowervm/adapter.py:404
#, python-format
msgid "suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr "risposta HTTP 401 sospetta per %(method)s %(path)s: il token è nuovo"

#: pypowervm/adapter.py:456
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""
"Impossibile connettersi al server REST - il servizio pvm-rest è stato avviato?  "
"Nuovo tentativo %(try_num)d di %(max_tries)d dopo %(delay)d secondi."

#: pypowervm/adapter.py:463
#, python-format
msgid "Session logging on %s"
msgstr "Logon sessione %s"

#: pypowervm/adapter.py:526
msgid "Failed to parse a session token from the PowerVM response."
msgstr "Impossibile analizzare un token sessione dalla risposta PowerVM."

#: pypowervm/adapter.py:528 pypowervm/adapter.py:544
#, python-format
msgid " Body= %s"
msgstr " Corpo= %s"

#: pypowervm/adapter.py:542
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "Impossibile analizzare un percorso file sessione dalla risposta PowerVM."

#: pypowervm/adapter.py:556
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "Il file token %s non contiene un token sessione leggibile."

#: pypowervm/adapter.py:566
#, python-format
msgid "Session logging off %s"
msgstr "Logoff sessione %s"

#: pypowervm/adapter.py:571
msgid "Problem logging off.  Ignoring."
msgstr "Problema nel logoff.  Ignorato."

#: pypowervm/adapter.py:673
msgid "job must be a JobRequest element"
msgstr "il lavoro deve essere un elemento JobRequest"

#: pypowervm/adapter.py:677
msgid "JobRequest is missing OperationName"
msgstr "In JobRequest manca OperationName"

#: pypowervm/adapter.py:691 pypowervm/adapter.py:847 pypowervm/adapter.py:900
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "il percorso=%s non è un riferimento API PowerVM"

#: pypowervm/adapter.py:809
#, python-format
msgid "path=%s not a PowerVM API reference"
msgstr "il percorso=%s non è un riferimento API PowerVM"

#: pypowervm/adapter.py:915 pypowervm/adapter.py:932
msgid "Invalid file descriptor"
msgstr "Descrittore file non valido"

#: pypowervm/adapter.py:1018 pypowervm/adapter.py:1046
#: pypowervm/adapter.py:1061
msgid "Expected root_id"
msgstr "Previsto root_id"

#: pypowervm/adapter.py:1020
msgid "Expected child_type"
msgstr "Previsto child_type"

#: pypowervm/adapter.py:1024 pypowervm/adapter.py:1050
#: pypowervm/adapter.py:1055
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "suffix_type=%s non previsto"

#: pypowervm/adapter.py:1027 pypowervm/adapter.py:1058
msgid "Expected suffix_parm"
msgstr "Previsto suffix_parm"

#: pypowervm/adapter.py:1029 pypowervm/adapter.py:1048
#: pypowervm/adapter.py:1063
msgid "Expected child_id"
msgstr "Previsto child_id"

#: pypowervm/adapter.py:1032 pypowervm/adapter.py:1041
msgid "Unexpected child_id"
msgstr "child_id non previsto"

#: pypowervm/adapter.py:1034 pypowervm/adapter.py:1043
msgid "Unexpected root_id"
msgstr "root_id non previsto"

#: pypowervm/adapter.py:1065
#, python-format
msgid "Unexpected req_method=%s"
msgstr "req_method=%s non previsto"

#: pypowervm/adapter.py:1133
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "Errore durante l'analisi della risposta XML da PowerVM: %s"

#: pypowervm/adapter.py:1146
msgid "Response is not an Atom feed/entry"
msgstr "La risposta non è un feed/voce atom"

#: pypowervm/adapter.py:1157
msgid "Unexpected HTTP 204 for request"
msgstr "Errore HTTP 204 imprevisto per la richiesta"

#: pypowervm/adapter.py:1165
msgid "Unexpectedly empty response body"
msgstr "Corpo della risposta inaspettatamente vuoto"

#: pypowervm/adapter.py:1168
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s:\n"
"intestazioni richiesta: %(reqheaders)s\n"
"\n"
"corpo richiesta: %(reqbody)s\n"
"\n"
"intestazioni risposta: %(respheaders)s\n"
"\n"
"corpo risposta: %(respbody)s"

#: pypowervm/adapter.py:1176
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "Errore atom per %(method)s %(path)s: %(reason)s"

#: pypowervm/adapter.py:1217
msgid "Session must not be None"
msgstr "La sessione non deve essere Nessuno"

#: pypowervm/adapter.py:1219
msgid "An event listener is already active on the session."
msgstr "Un listener di eventi è già attivo nella sessione."

#: pypowervm/adapter.py:1238
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "Impossibile inizializzare il listener feed eventi: %s"

#: pypowervm/adapter.py:1242
#, python-format
msgid "Application id \"%s\" not unique"
msgstr "L'ID applicazione \"%s\" non è univoco"

#: pypowervm/adapter.py:1250
msgid "Shutting down"
msgstr "In arresto"

#: pypowervm/adapter.py:1253
msgid "This handler is already subscribed"
msgstr "Questo gestore è già sottoscritto"

#: pypowervm/adapter.py:1261
msgid "Handler must be an EventHandler"
msgstr "Il gestore deve essere un gestore eventi"

#: pypowervm/adapter.py:1264
msgid "Handler not found in subscriber list"
msgstr "Gestore non trovato nell'elenco di sottoscrittori"

#: pypowervm/adapter.py:1271
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "Chiusura del listener di eventi per %s"

#: pypowervm/adapter.py:1275
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "Chiusura listener di eventi completata per %s"

#: pypowervm/adapter.py:1295
#, python-format
msgid "Error while getting PowerVM events: %s.  (Is the pvm-rest service down?)"
msgstr "Errore durante l'ottenimento di eventi PowerVM: %s.  (Il servizio pvm-rest è inattivo?)"

#: pypowervm/adapter.py:1338
#, python-format
msgid "Unexpected EventType=%s"
msgstr "EventType=%s imprevisto"

#: pypowervm/adapter.py:1365
msgid "Error while processing PowerVM events"
msgstr "Errore durante l'elaborazione degli eventi PowerVM"

#: pypowervm/exceptions.py:127
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"Impossibile derivare la porta FC fisica appropriata per WWPN %(wwpn)s.  I"
" gruppi di attributi estesi VIOS potrebbero essere stati insufficienti.  L'URI VIOS"
" per la query era %(vio_uri)s."

#: pypowervm/exceptions.py:133
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Elemento non trovato: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:137
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "LPAR non trovata: %(lpar_name)s"

#: pypowervm/exceptions.py:141
msgid "Adapter not found"
msgstr "Adattatore non trovato"

#: pypowervm/exceptions.py:145
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "Operazione '%(operation_name)s' non riuscita. %(error)s"

#: pypowervm/exceptions.py:149
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"L'operazione '%(operation_name)s' non è riuscita. Impossibile completare l'attività in"
" %(seconds)d secondi."

#: pypowervm/exceptions.py:154
#, python-format
msgid ""
"Can not perform OS shutdown on Virtual Machine %(lpar_nm)s because its "
"RMC connection is not active."
msgstr ""
"Impossibile eseguire la chiusura del sistema operativo sulla macchina virtuale %(lpar_nm)s, perché "
"la relativa connessione RMC non è attiva."

#: pypowervm/exceptions.py:159
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Impossibile spegnere la macchina virtuale %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:163
#, python-format
msgid ""
"Power off of Virtual Machine %(lpar_nm)s timed out after %(timeout)d "
"seconds."
msgstr ""
"Spegnimento della macchina virtuale %(lpar_nm)s scaduto dopo %(timeout)d "
"secondi."

#: pypowervm/exceptions.py:168
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Impossibile accendere la macchina virtuale %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:172
#, python-format
msgid ""
"Power on of Virtual Machine %(lpar_nm)s timed out after %(timeout)d "
"seconds."
msgstr ""
"Accensione della macchina virtuale %(lpar_nm)s scaduta dopo %(timeout)d "
"secondi."

#: pypowervm/exceptions.py:177
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"Impossibile rimuovere la VLAN %(vlan_id)d, poiché è l'identificativo VLAN primario su"
" un bridge di rete differente."

#: pypowervm/exceptions.py:182
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"Impossibile eseguire il provisioning della VLAN %(vlan_id)d.  Sembra che sia contenuta nel "
"dispositivo '%(dev_name)s' sul Virtual I/O Server %(vios)s.  Questo dispositivo non è"
" connesso ad alcun bridge di rete (Shared Ethernet Adapter).  Rimuovere "
"manualmente il dispositivo o aggiungerlo al bridge di rete, prima "
"di continuare."

#: pypowervm/exceptions.py:191
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Una LU (Logical Unit) con il nome %(lu_name)s esiste già sul pool di memoria "
"condivisa %(ssp_name)s."

#: pypowervm/exceptions.py:196
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"Impossibile trovare una porta fisica a cui associare una porta Fibre Channel virtuale.  "
"Questo è dovuto alla indisponibilità di un Virtual I/O Server o a una specifica"
" della porta non corretta per le porte Fibre Channel fisiche."

#: pypowervm/exceptions.py:203
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Impossibile avviare la console per la macchina virtuale.  L'API pypowervm è"
" in esecuzione in modalità non locale.  La console può essere distribuita solo quando "
"pypowervm si trova nella stessa ubicazione dell'API PowerVM."

#: pypowervm/exceptions.py:210
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s non ha attività secondarie."

#: pypowervm/exceptions.py:214
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask non può avere un feed vuoto."

#: pypowervm/exceptions.py:218
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "L'SO ha negato l'accesso al file %(access_file)s."

#: pypowervm/exceptions.py:222
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"L'SO ha rilevato un errore I/O nel tentativo di leggere il file %(access_file)s: "
"%(error)s"

#: pypowervm/exceptions.py:227
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "Attività di migrazione non riuscita. %(error)s"

#: pypowervm/exceptions.py:231
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Nessuna origine di caricamento trovata per la VM %(vm_name)s"

#: pypowervm/exceptions.py:235
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The "
"parent_entry attribute is not set.  This may be due to using a PV "
"obtained through an unsupported property chain.  The PV must be accessed "
"via VIOS.phys_vols, VG.phys_vols, or "
"VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"Impossibile derivare la codifica pg83 per l'hdisk %(dev_name)s.  L'attributo "
"parent_entry non è impostato.  Ciò può essere dovuto all'utilizzo di un PV "
"ottenuto tramite una catena di proprietà non supportata.  È necessario accedere al PV "
"tramite VIOS.phys_vols, VG.phys_vols, oppure "
"VIOS.scsi_mappings[n].backing_storage."

#: pypowervm/exceptions.py:243
#, python-format
msgid ""
"Unable to remap storage element of vSCSI mapping. Expected to find "
"exactly one matching mapping, found %(num_mappings)d."
msgstr ""
"Impossibile riassociare l'elemento di memoria dell'associazione vSCSI. Era previsto trovare "
"esattamente un'associazione corrispondente, trovate %(num_mappings)d."

#: pypowervm/exceptions.py:249
#, python-format
msgid ""
"Unable to remap storage element of vSCSI mapping. A mapping for storage "
"element %(stg_name)s already exists to client LPAR %(lpar_uuid)s."
msgstr ""
"Impossibile riassociare l'elemento di memoria dell'associazione vSCSI. Un'associazione per "
"l'elemento di memoria %(stg_name)s esiste già sulla LPAR client %(lpar_uuid)s."

#: pypowervm/exceptions.py:255
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most "
"once."
msgstr ""
"Il dispositivo %(devname)s è stato trovato %(count)d volte; era previsto che venisse trovato al massimo "
"una sola volta."

#: pypowervm/exceptions.py:270
#, python-format
msgid ""
"FeedTask %(ft_name)s experienced multiple exceptions:\n"
"\t%(concat_msgs)s"
msgstr ""
"L'attività feed %(ft_name)s ha emesso diverse eccezioni:\n"
"\t%(concat_msgs)s"

#: pypowervm/exceptions.py:280
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Era previsto trovare una sola partizione di gestione; trovate %(count)d."

#: pypowervm/exceptions.py:286
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found "
"%(count)d."
msgstr ""
"Era previsto trovare esattamente una singola partizione con ID %(lpar_id)d; trovate "
"%(count)d."

#: pypowervm/exceptions.py:292
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr "Impossibile trovare il pool di memoria condiviso o di livello predefinito %(ssp_name)s."

#: pypowervm/exceptions.py:301
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""
"Il dispositivo con UDID %(udid)s non è stato trovato su alcun Virtual I/O "
"Server."

#: pypowervm/exceptions.py:306
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's"
" device with UDID %(udid)s."
msgstr ""
"Non sono presenti Virtual I/O Server sufficienti per supportare il dispositivo"
" della macchina virtuale con UDID %(udid)s."

#: pypowervm/exceptions.py:311
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual "
"I/O Servers."
msgstr ""
"I fabric previsti (%(fabrics)s) non sono stati trovati su alcun Virtual "
"I/O Server."

#: pypowervm/exceptions.py:316
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of "
"%(io_type)s which is not supported for VM rebuild."
msgstr ""
"Impossibile ricreare la macchina virtuale.  Sta utilizzando un tipo I/O "
"%(io_type)s, che non è supportato per la nuova creazione della macchina virtuale."

#: pypowervm/exceptions.py:321
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not"
" match the number of slots on the client system (%(original_slots)d).  "
"Unable to rebuild this virtual machine on this system."
msgstr ""
"Il numero di slot VFC sul sistema di destinazione (%(rebuild_slots)d) non"
" corrisponde al numero di slot sul sistema client %(original_slots)d).  "
"Impossibile ricreare questa macchina virtuale su questo sistema."

#: pypowervm/exceptions.py:328
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC "
"adapter is needed. Instead the following was given: %(wrapper)s."
msgstr ""
"Per registrare le informazioni sullo slot del dispositivo di rete, è necessario un adattatore "
"CNA o VNIC. È stato invece fornito quanto segue: %(wrapper)s."

#: pypowervm/exceptions.py:334
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected "
"%(exp)d; found %(act)d."
msgstr ""
"Non sono disponibili Virtual I/O Server attivi sufficienti. Previsti "
"%(exp)d; trovati %(act)d."

#: pypowervm/exceptions.py:339
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC "
"connectivity between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""
"Non è disponibile alcun Virtual I/O Server.  Tentativo di attesa che un VIOS "
"diventi attivo per %(wait_time)d secondi.  Controllare la connettività "
"RMC tra PowerVM NovaLink e i Virtual I/O Server."

#: pypowervm/exceptions.py:349
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""
"Impossibile trovare adattatori SR-IOV in modalità Sriov e in stato In esecuzione.\n"
"Ubicazione | Modalità | Stato\n"
"%(sriov_loc_mode_state)s"

#: pypowervm/exceptions.py:354
#, python-format
msgid ""
"Unable to fulfill redundancy requirement of %(red)d.  Found %(found_vfs)d"
" viable backing device(s)."
msgstr ""
"Impossibile soddisfare i requisiti di ridondanza di %(red)d.  Trovati %(found_vfs)d"
" dispositivi di backup utilizzabili."

#: pypowervm/exceptions.py:359
msgid "The Managed System is not vNIC capable."
msgstr "Il sistema gestito non supporta vNIC."

#: pypowervm/exceptions.py:363
msgid "There are no active vNIC-capable VIOSes."
msgstr "Non ci sono VIOS che supportano vNIC attive."

#: pypowervm/exceptions.py:367
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but the Managed System is not vNIC"
" failover capable."
msgstr ""
"È stata specificata una ridondanza di %(red)d ma il sistema gestito non"
" supporta il failover vNIC."

#: pypowervm/exceptions.py:372
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but there are no active vNIC "
"failover-capable VIOSes."
msgstr ""
"È stata specificata una ridondanza %(red)d, ma non sono presenti VIOS "
"che supportano il failover vNIC attivi."

#: pypowervm/exceptions.py:377
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Impossibile individuare il gruppo di volumi %(vol_grp)s per memorizzarvi i supporti ottici "
"virtuali.  Impossibile creare il repository di supporti."

#: pypowervm/exceptions.py:383
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested"
" to one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""
"L'aggiornamento ManagedSystem non è stato tentato perché erano richieste delle modifiche"
" a una o più porte fisiche SR-IOV che sono utilizzate dalle vNIC.\n"
"%(warnings)s"

#: pypowervm/exceptions.py:389
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr "Impossibile creare il terminale virtuale basato su VNC: %(err)s"

#: pypowervm/exceptions.py:393
msgid "The Adapter cache is not supported."
msgstr "La cache adattatore non è supportata."

#: pypowervm/exceptions.py:397
#, python-format
msgid ""
"Invalid value '%(value)s' for '%(enum)s'.  Valid values are: "
"%(valid_values)s"
msgstr ""
"Valore non valido '%(value)s' per '%(enum)s'.  Valori validi sono: "
"%(valid_values)s"

#: pypowervm/exceptions.py:402
#, python-format
msgid "No VIOS found with name %(vios_name)s."
msgstr "Nessun VIOS trovato con nome %(vios_name)s."

#: pypowervm/exceptions.py:406
#, python-format
msgid "No volume group found with name %(vg_name)s."
msgstr "Nessun gruppo di volumi trovato con nome %(vg_name)s."

#: pypowervm/exceptions.py:410
#, python-format
msgid "Partition with name %(part_name)s is not an IBMi partition."
msgstr "La partizione con nome %(part_name)s non è una partizione IBMi."

#: pypowervm/exceptions.py:414
msgid "PanelJob function partition argument is empty."
msgstr "Argomento partizione della funzione PanelJob vuoto."

#: pypowervm/exceptions.py:418
#, python-format
msgid ""
"Panel function operation %(op_name)s is invalid. One of %(valid_ops)s "
"expected."
msgstr ""
"Operazione funzione pannello %(op_name)s non valida. Una tra %(valid_ops)s "
"prevista."

#: pypowervm/exceptions.py:423
#, python-format
msgid "ISCSI discovery failed for VIOS %(vios_uuid)s. Return code: %(status)s"
msgstr "Rilevamento ISCSI non riuscito per %(vios_uuid)s. Codice di ritorno: %(status)s"

#: pypowervm/exceptions.py:429
#, python-format
msgid "ISCSI Logout failed for VIOS %(vios_uuid)s. Return code: %(status)s"
msgstr "Logout ISCSI non riuscito per %(vios_uuid)s. Codice di ritorno: %(status)s"

#: pypowervm/exceptions.py:434
#, python-format
msgid "ISCSI Remove failed for VIOS %(vios_uuid)s. Return code: %(status)s"
msgstr "Rimozione di ISCSI non riuscita per VIOS %(vios_uuid)s. Codice di ritorno: %(status)s"

#: pypowervm/exceptions.py:439
#, python-format
msgid "Vstor %(stor_udid)s not found for VIOS %(vios_uuid)s."
msgstr "Vstor %(stor_udid)s non trovato per VIOS %(vios_uuid)s."

#: pypowervm/util.py:125
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"Il gruppo di attributi estesi proposto '%(arg_xag)s' non corrisponde al "
"gruppo di attributi estesi esistente '%(path_xag)s'"

#: pypowervm/util.py:221
msgid "Certificate has expired."
msgstr "Il certificato è scaduto."

#: pypowervm/util.py:371
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Il prefisso e il suffisso insieme non possono superare i %d caratteri."

#: pypowervm/util.py:376
msgid "Total length must be at least 1 character."
msgstr "La lunghezza totale deve essere di almeno 1 carattere."

#: pypowervm/util.py:399
msgid "The name parameter must be at least one character long."
msgstr "Il parametro del nome deve essere lungo almeno un carattere."

#: pypowervm/util.py:402
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "Il parametro del nome non deve superare i %d caratteri quando trunk_ok è False."

#: pypowervm/util.py:500
msgid "Developer error: partial parent specification."
msgstr "Errore sviluppatore: specifica parent parziale."

#: pypowervm/util.py:505
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"Errore sviluppatore: il tipo parent deve essere un tipo schema stringa o "
"una sottoclasse Wrapper."

#: pypowervm/util.py:602
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr "Valore non valido '%(bad_val)s'.  Era previsto uno di %(good_vals)s oppure un elenco."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "RICHIESTA: %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "RISPOSTA: %s"

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "In attesa del completamento dei caricamenti in corso.  LU indicatori: %s"

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr "Interruzione in favore del caricamento in corso."

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "Interruzione caricamento in favore dell'indicatore %s."

#: pypowervm/tasks/cluster_ssp.py:202
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "Utilizzo della LU immagine già caricata %s."

#: pypowervm/tasks/cluster_ssp.py:212
#, python-format
msgid "Creating marker LU %s"
msgstr "Creazione della LU indicatore %s"

#: pypowervm/tasks/cluster_ssp.py:228
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "Caricamento della LU immagine %(lu)s (indicatore %(mkr)s)."

#: pypowervm/tasks/cluster_ssp.py:240
#, python-format
msgid "Removing failed LU %s."
msgstr "Rimozione della LU malfunzionante %s."

#: pypowervm/tasks/cna.py:119
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Impossibile trovare lo switch virtuale %s sul sistema."

#: pypowervm/tasks/cna.py:143
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "Impossibile trovare una VLAN valida VLAN per lo switch virtuale %s."

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Errore nell'ottenere il sovraccarico di memoria host per l'host con UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/partition.py:333
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did "
"not go active were: %(vioses)s."
msgstr ""
"Timeout mentre si attendeva che lo stato RMC di tutti i Virtual I/O "
"Server accesi indicasse una condizione di attivo. Il tempo di attesa era: %(time)d secondi. I VIOS che "
"non sono diventati attivi erano: %(vioses)s."

#: pypowervm/tasks/partition.py:376
#, python-format
msgid "Assuming description-less slot is physical I/O: %s"
msgstr "Si assume che lo slot senza descrizione sia I/O fisico: %s"

#: pypowervm/tasks/power.py:88
#, python-format
msgid "Partition %s already powered on."
msgstr "Partizione %s già accesa."

#: pypowervm/tasks/power.py:136
#, python-format
msgid "Partition %s already powered off."
msgstr "Partizione %s già spenta."

#: pypowervm/tasks/power.py:199
#, python-format
msgid ""
"Specifying add_parms as a dict is deprecated. Please specify a %s "
"instance instead."
msgstr ""
"La specifica di add_parms come dict è obsoleta. Specificare un'istanza %s "
"invece."

#: pypowervm/tasks/power.py:265
#, python-format
msgid ""
"IBMi OS normal shutdown failed.  Trying OS immediate shutdown.  "
"Partition: %s"
msgstr ""
"Arresto regolare del sistema operativo IBMi non riuscito.  Tentativo di arresto immediato del sistema operativo.  "
"Partizione: %s"

#: pypowervm/tasks/power.py:275
#, python-format
msgid ""
"IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""
"Arresto immediato del sistema operativo IBMi non riuscito.  Tentativo di arresto regolare VSP.  "
"Partizione: %s"

#: pypowervm/tasks/power.py:323
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown timed out.  Trying VSP hard shutdown.  "
"Partition: %s"
msgstr ""
"Arresto immediato sistema operativo non IBMi scaduto.  Tentativo di arresto a freddo VSP.  "
"Partizione: %s"

#: pypowervm/tasks/power.py:327
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""
"Arresto immediato del sistema operativo non IBMi non riuscito.  Tentativo di arresto regolare VSP.  "
"Partizione: %s"

#: pypowervm/tasks/power.py:363
#, python-format
msgid "VSP hard shutdown with default timeout.  Partition: %s"
msgstr "Arresto a freddo VSP con timeout predefinito.  Partizione: %s"

#: pypowervm/tasks/scsi_mapper.py:39
msgid "Retrying modification of SCSI Mapping."
msgstr "Nuovo tentativo di modifica dell'associazione SCSI."

#: pypowervm/tasks/scsi_mapper.py:99
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Trovata un'associazione esistente dell'elemento di memoria %(stg_type)s %(stg_name)s "
"dal Virtual I/O Server %(vios_name)s alla LPAR client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:118
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Creazione dell'associazione dell'elemento di memoria %(stg_type)s %(stg_name)s dal "
"Virtual I/O Server %(vios_name)s alla LPAR client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:489
msgid "Must not specify both match_func and stg_elem."
msgstr "Non si devono specificare entrambi match_func e stg_elem."

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet "
"method."
msgstr ""
"Il metodo register_cna è obsoleto. Utilizzare il metodo "
"register_vnet."

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr "Il metodo drop_cna è obsoleto. Utilizzare il metodo drop_vnet."

#: pypowervm/tasks/sriov.py:398
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging"
" to LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: "
"%(vnic_uuid)s)."
msgstr ""
"La porta fisica SR-IOV nell'ubicazione %(loc_code)s sta supportando una vNIC che appartiene"
" alla LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: "
"%(vnic_uuid)s)."

#: pypowervm/tasks/sriov.py:515
msgid ""
"Making changes to the following SR-IOV physical port labels even though "
"they are in use by vNICs:"
msgstr ""
"Si stanno apportando modifiche alle seguenti etichette di porta fisica SR-IOV, anche se "
"sono utilizzate dalle vNIC:"

#: pypowervm/tasks/storage.py:100
#, python-format
msgid "Failed to delete vio_file with UUID %s.  It must be manually deleted."
msgstr "Impossibile eliminare vio_file con UUID %s.  Deve essere eliminato manualmente."

#: pypowervm/tasks/storage.py:356
msgid "Encountered an issue while uploading. Will retry."
msgstr "È stato riscontrato un problema durante il caricamento. Verrà effettuato un nuovo tentativo."

#: pypowervm/tasks/storage.py:530
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu "
"method (clone=src_lu, size=lu_size_gb)."
msgstr ""
"Il metodo crt_lu_linked_clone è obsoleto.  Utilizzare il metodo crt_lu "
"(clone=src_lu, size=lu_size_gb)."

#: pypowervm/tasks/storage.py:581
#, python-format
msgid "Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr "La LU (Logical Unit) disco %(luname)s non ha alcuna LU immagine di supporto.  (UDID: %(udid)s) "

#: pypowervm/tasks/storage.py:665
msgid "Unable to locate new vDisk on file upload."
msgstr "Impossibile individuare il nuovo vDisk sul caricamento file."

#: pypowervm/tasks/storage.py:752
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"Il dispositivo verrà ignorato perché gli manca un UDID:\n"
"%s"

#: pypowervm/tasks/storage.py:758
#, python-format
msgid "Device %s not found in list."
msgstr "Dispositivo %s non trovato nell'elenco."

#: pypowervm/tasks/storage.py:787
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Eliminazione del disco virtuale %(vdisk)s dal gruppo di volumi %(vg)s"

#: pypowervm/tasks/storage.py:810
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Eliminazione del dispositivo ottico virtuale %(vopt)s dal gruppo di volumi %(vg)s"

#: pypowervm/tasks/storage.py:866
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "Rimozione della LU %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:870
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"La LU %(lu_name)s non è stata trovata, potrebbe essere stata eliminata fuori banda.  "
"(UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:888
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"Rimozione della LU immagine %(lu_name)s perché non è più in uso.  (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:893
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "La LU di supporto %(lu_name)s non è stata trovata.  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:919
msgid "Developer error: Either tier or lufeed is required."
msgstr "Errore sviluppatore: è richiesto il livello o lufeed."

#: pypowervm/tasks/storage.py:924
msgid "Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr "Errore sviluppatore: il parametro lufeed deve comprendere LUEnt EntryWrappers."

#: pypowervm/tasks/storage.py:931
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "Eliminazione LU %(lu_name)s (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:936
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band."
"  (UDID: %(lu_udid)s)"
msgstr ""
"Si ignora HttpError per LU %(lu_name)s, potrebbe essere stata eliminata fuori banda."
"  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:992
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Rimozione di %(num_maps)d associazioni %(stg_type)s orfane da VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:1018
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "Rimozione di %(num_maps)d associazioni VFC senza porta dal VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:1045
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Rimozione di %(num_maps)d associazioni %(stg_type)s associate all'ID LPAR "
"%(lpar_id)d dal VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:1112
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot "
"be determined whether it is still in use.  Manual verification and "
"cleanup may be necessary."
msgstr ""
"Non viene rimossa la memoria %(stg_name)s di tipo %(stg_type)s, perché non è possibile "
"determinare se è ancora in uso.  Potrebbero essere necessari una verifica e "
"un cleanup manuali."

#: pypowervm/tasks/storage.py:1123
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"Scrub memoria ignora l'elemento memoria %(stg_name)s perché è "
"del tipo imprevisto %(stg_type)s."

#: pypowervm/tasks/storage.py:1141
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Ripulitura dei seguenti %(vdcount)d dischi virtuali dal VIOS %(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:1149
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Ripulitura dei seguenti %(vocount)d dispositivi ottici virtuali dal VIOS %(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:1220
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Ignorato scrub di associazioni %(stg_type)s dal VIOS %(vios_name)s per i "
"seguenti ID LPAR perché tali LPAR esistono: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:543
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Impossibile trovare il VIOS appropriato.  Il payload fornito probabilmente era "
"insufficiente.  I dati di payload sono:\n"
" %s)"

#: pypowervm/tasks/vfc_mapper.py:572
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to "
"mapping for client wwpns: %(wwpns)s"
msgstr ""
"Per l'associazione di porta VFC messa in corrispondenza non è impostata alcuna porta di supporto. Aggiunta di %(port)s "
"all'associazione per i wwpn client: %(wwpns)s"

#: pypowervm/tasks/vopt.py:75
msgid ""
"An error occurred querying the virtual optical media repository.  "
"Attempting to re-establish connection with a virtual optical media "
"repository."
msgstr ""
"Si è verificato un errore durante la query del repository di supporti ottici virtuali.  "
"Tentativo di ristabilire la connessione con un repository di supporti ottici "
"virtuali."

#: pypowervm/tasks/vterm.py:86
msgid "Unable to close vterm."
msgstr "Impossibile chiudere vterm."

#: pypowervm/tasks/vterm.py:138
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr "Output non valido sull'apertura di vterm.  Tentativo di reimpostare il vterm.  L'errore era %s"

#: pypowervm/tasks/vterm.py:351
#, python-format
msgid "VNCSocket Listener Listening on ip=%(ip)s port=%(port)s"
msgstr "Listener VNCSocket in ascolto su ip=%(ip)s porta=%(port)s"

#: pypowervm/tasks/vterm.py:480
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr "Errore di negoziazione SSL per il VNC Repeater: %s"

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"Rilevamento hdisk non riuscito; verrà ripulita la memoria obsoleta per gli ID LPAR %s e "
"verrà fatto un nuovo tentativo."

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Ripristino LUA riuscito. Dispositivo trovato: %s"

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Riscontrato errore ITL: %s"

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "Il dispositivo %s è attualmente è in uso."

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Dispositivo %s rilevato con UDID sconosciuto."

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Rilevamento del dispositivo non riuscito: %s"

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Errore CLIRunner: %s"

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"Lavoro di ripristino QUERY_INVENTORY LUA riuscito ma il risultato non contiene "
"OutputXML né StdOut."

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid "QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr "QUERY_INVENTORY ha prodotto un chunk di XML (%(chunk)s) non valido.  Errore: %(err)s"

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"Impossibile trovare il descrittore pg83 nell'output XML:\n"
"%s"

#: pypowervm/tasks/hdisk/_iscsi.py:64
msgid "ISCSI command completed successfully"
msgstr "Comando ISCSI completato correttamente"

#: pypowervm/tasks/hdisk/_iscsi.py:66
msgid "ISCSI session already exists and logged in"
msgstr "Sessione ISCSI già esistente e collegata"

#: pypowervm/tasks/hdisk/_iscsi.py:68
msgid "ISCSI command performed on unsupported VIOS, host."
msgstr "Comando ISCSI eseguito su host, VIOS non supportato. "

#: pypowervm/tasks/hdisk/_iscsi.py:71
msgid "ISCSI discovery found stale entries in the ODM database."
msgstr "Il rilevamento ISCSI ha individuato voci obsolete nel database ODM."

#: pypowervm/tasks/hdisk/_iscsi.py:74
msgid "ISCSI session could not be found "
msgstr "Impossibile trovare la sessione ISCSI "

#: pypowervm/tasks/hdisk/_iscsi.py:76
msgid "No records/targets/sessions/portals found to execute operation on"
msgstr "Nessun record/destinazione/sessione/portale trovato su cui eseguire l'operazione"

#: pypowervm/tasks/hdisk/_iscsi.py:79
#, python-format
msgid "ISCSI command failed with internal error status = %s"
msgstr "Comando ISCSI non riuscito con stato errore interno = %s"

#: pypowervm/tasks/hdisk/_iscsi.py:82
msgid "ISCSI generic error code"
msgstr "Codice di errore ISCSI generico"

#: pypowervm/tasks/hdisk/_iscsi.py:84
msgid "ISCSI session login failure"
msgstr "Errore di accesso alla sessione ISCSI"

#: pypowervm/tasks/hdisk/_iscsi.py:86
msgid "ISCSI command invalid arguments"
msgstr "Comando ISCSI con argomenti non validi"

#: pypowervm/tasks/hdisk/_iscsi.py:88
msgid "ISCSI connection timer exired while trying to connect."
msgstr "Timer di connessione ISCSI scaduto durante il tentativo di connessione. "

#: pypowervm/tasks/hdisk/_iscsi.py:90
msgid "ISCSI command could not lookup host"
msgstr "Il comando ISCSI non è stato in grado di ricercare l'host"

#: pypowervm/tasks/hdisk/_iscsi.py:92
#, python-format
msgid "ISCSI command returned unexpected status = %s"
msgstr "Il comando ISCSI ha restituito uno stato imprevisto = %s"

#: pypowervm/tasks/hdisk/_iscsi.py:151
msgid "ISCSI command performed on unsupported VIOS "
msgstr "Comando ISCSI eseguito su un VIOS non supportato"

#: pypowervm/tasks/hdisk/_iscsi.py:287
#, python-format
msgid "Scrub stale storage for LPAR IDs %s and retry iSCSI discovery."
msgstr "Ripulire la memoria obsoleta per gli ID LPAR %s e ripetere il rilevamento iSCSI."

#: pypowervm/tasks/monitor/util.py:452
msgid ""
"Metric data is not available.  This may be due to the metrics being "
"recently initialized."
msgstr ""
"I dati di metrica non sono disponibili.  Ciò può essere dovuto al fatto che le metriche sono state "
"recentemente inizializzate."

#: pypowervm/tests/test_i18n.py:34
msgid "This is a test"
msgstr "Questo è un test"

#: pypowervm/tests/test_i18n.py:37
msgid "This is a message for which a translation doesn't exist"
msgstr "Questo è un messaggio per il quale non esiste una traduzione"

#: pypowervm/utils/lpar_builder.py:216
#, python-format
msgid "Processor units factor must be between 0.05 and 1.0. Value: %s"
msgstr "Il fattore unità  processore deve essere tra 0.05 e 1.0. Valore: %s"

#: pypowervm/utils/lpar_builder.py:244
#, python-format
msgid "Logical partition name has invalid length. Name: %s"
msgstr "Il nome partizione logica ha una lunghezza non valida. Nome: %s"

#: pypowervm/utils/lpar_builder.py:448
#, python-format
msgid "Field '%(field)s' has invalid value: '%(value)s'"
msgstr "Il campo '%(field)s' ha un valore non valido: '%(value)s'"

#: pypowervm/utils/lpar_builder.py:503
msgid "None value is not valid."
msgstr "Il valore Nessuno non è valido."

#: pypowervm/utils/lpar_builder.py:510
#, python-format
msgid ""
"Value '%(value)s' is not valid for field '%(field)s' with acceptable "
"choices: %(choices)s"
msgstr ""
"Il valore '%(value)s' non è valido per il campo '%(field)s' con "
"scelte accettabili: %(choices)s"

#: pypowervm/utils/lpar_builder.py:535
#, python-format
msgid ""
"Field '%(field)s' has a value below the minimum. Value: %(value)s; "
"Minimum: %(minimum)s"
msgstr ""
"Il campo '%(field)s' ha un valore al di sotto del minimo. Valore: %(value)s; "
"Minimo: %(minimum)s"

#: pypowervm/utils/lpar_builder.py:544
#, python-format
msgid ""
"Field '%(field)s' has a value above the maximum. Value: %(value)s; "
"Maximum: %(maximum)s"
msgstr ""
"Il campo '%(field)s' ha un valore al di sopra del massimo. Valore: %(value)s; "
"Massimo: %(maximum)s"

#: pypowervm/utils/lpar_builder.py:598
#, python-format
msgid ""
"The '%(desired_field)s' has a value above the '%(max_field)s' value. "
"Desired: %(desired)s Maximum: %(maximum)s"
msgstr ""
"'%(desired_field)s' ha un valore superiore al valore '%(max_field)s'. "
"Desiderato: %(desired)s Massimo: %(maximum)s"

#: pypowervm/utils/lpar_builder.py:611
#, python-format
msgid ""
"The '%(desired_field)s' has a value below the '%(min_field)s' value. "
"Desired: %(desired)s Minimum: %(minimum)s"
msgstr ""
"'%(desired_field)s' ha un valore inferiore al valore '%(min_field)s'. "
"Desiderato: %(desired)s Minimo: %(minimum)s"

#: pypowervm/utils/lpar_builder.py:655
#, python-format
msgid ""
"Memory value is not a multiple of the logical memory block size "
"(%(lmb_size)s) of  the host.  Value: %(value)s"
msgstr ""
"Il valore di memoria non è un multiplo della dimensione di blocco della memoria logica "
"(%(lmb_size)s) dell'host.  Valore: %(value)s"

#: pypowervm/utils/lpar_builder.py:666
#, python-format
msgid ""
"The managed system does not support active memory expansion. The "
"expansion factor value '%(value)s' is not valid."
msgstr ""
"Il sistema gestito non supporta l'espansione di memoria attiva. Il "
"valore del fattore di espansione '%(value)s' non è valido."

#: pypowervm/utils/lpar_builder.py:672
#, python-format
msgid ""
"Active memory expansion value must be greater than or equal to 1.0 and "
"less than or equal to 10.0. A value of 0 is also valid and indicates that"
" AME is off. '%(value)s' is not valid."
msgstr ""
"Il valore di espansione di memoria attiva deve essere maggiore di o uguale a 1.0 e "
"inferiore o uguale a 10.0. È valido anche un valore 0 è valido e indica che"
" AME è spento. '%(value)s' non è valido."

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Tentativo %(retry)d di %(total)d totali per l'URI %(uri)s.  L'errore è un "
"codice di risposta di nuovo tentativo noto: %(resp_code)s"

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Tentativo %(retry)d di %(total)d non riuscito.  Verrà effettuato un nuovo tentativo. L'eccezione è:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "È necessario fornire EntryWrapper o EntryWrapperGetter."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "È necessario fornire un'attività secondaria valida."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Nome 'provides' duplicato %s."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s non ha attività secondarie; nessuna operazione in esecuzione."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "È necessario fornire un elenco di EntryWrappers o un FeedGetter."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s non ha attività secondarie; nessuna operazione in esecuzione."

#: pypowervm/utils/transaction.py:789
#, python-format
msgid ""
"FeedTask %s experienced multiple exceptions. They are logged individually"
" below."
msgstr ""
"L'attività feed %s ha emesso diverse eccezioni. Vengono registrate singolarmente"
" di seguito."

#: pypowervm/utils/validation.py:174
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"%(res_name)s disponibili non sufficienti sull'host per la macchina virtuale "
"'%(instance_name)s' (%(requested)s richiesti, %(avail)s disponibili)"

#: pypowervm/utils/validation.py:209
msgid "memory"
msgstr "di memoria"

#: pypowervm/utils/validation.py:230
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il valore minimo o "
"massimo di memoria. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:235
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il "
"fattore di espansione. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:328
msgid "CPUs"
msgstr "CPU"

#: pypowervm/utils/validation.py:344
msgid "processing units"
msgstr "unità di elaborazione"

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il valore minimo o "
"massimo di processori. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:395
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il valore minimo o "
"massimo di unità processore. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:411
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare la modalità "
"di compatibilità processore. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:419
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare la modalità "
"di elaborazione. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:448
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"I processori desiderati (%(vcpus)d) non possono essere più del numero massimo "
"di processori consentiti per partizione (%(max_allowed)d) per la macchina virtuale "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:460
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Il numero massimo di processori (%(vcpus)d) non può essere superiore al limite massimo "
"di processori della capacità di sistema (%(max_allowed)d) per la macchina virtuale "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:533
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare "
"la funzione di riavvio remoto semplificato. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/wrappers/base_partition.py:434
msgid "Partition does not have an active RMC connection."
msgstr "La partizione non ha una connessione RMC attiva."

#: pypowervm/wrappers/base_partition.py:437
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr "La partizione non ha una capacità DLPAR attiva per %s."

#: pypowervm/wrappers/base_partition.py:449
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/base_partition.py:459
msgid "Memory"
msgstr "Memoria"

#: pypowervm/wrappers/base_partition.py:469
msgid "Processors"
msgstr "Processori"

#: pypowervm/wrappers/base_partition.py:649
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos non valido '%s'."

#: pypowervm/wrappers/base_partition.py:660
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "Modalità di avvio non valida '%s'."

#: pypowervm/wrappers/base_partition.py:1501
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "IOSlot.adapter è obsoleto, utilizzare invece IOSlot.io_adapter."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the"
" master console for the pool."
msgstr ""
"Impossibile determinare la console di gestione master MTMS (tipo macchina, modello, "
"numero di serie) da %(identifier)s perché nessun %(param)s era contrassegnato come"
" console master per il pool."

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr "Impossibile impostare l'uuid."

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Impossibile convertire %(property_name)s='%(value)s' nell'oggetto %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Rifiuto impostazione di href su più link.\n"
"Percorso: %{path}s\n"
"Numero di link trovati: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:635
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Rifiuto di creare e includere un elemento senza tag."

#: pypowervm/wrappers/entry_wrapper.py:760
msgid "Response is missing 'entry' property."
msgstr "Alla risposta manca la proprietà 'entry'."

#: pypowervm/wrappers/entry_wrapper.py:774
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "È necessario fornire una risposta o una voce da includere.  Ottenuto %s"

#: pypowervm/wrappers/entry_wrapper.py:861
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to"
" retrieve a CHILD object."
msgstr ""
"Errore sviluppatore: specificare 'parent' o ('parent_type' e 'parent_uuid') per"
" richiamare un oggetto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:866
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "Specificare 'uuid' o 'root_id' quando si richiede un oggetto ROOT."

#: pypowervm/wrappers/entry_wrapper.py:879
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD "
"feed or entry."
msgstr ""
"Sono richiesti sia parent_type che parent_uuid quando si richiama un feed "
"o una voce CHILD."

#: pypowervm/wrappers/entry_wrapper.py:882
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "Specificare l'UUID de,l parent tramite il parametro parent_uuid."

#: pypowervm/wrappers/entry_wrapper.py:886
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "Specificare 'uuid' o 'child_id' quando si richiede un oggetto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:1001
msgid "Parent UUID specified without parent type."
msgstr "UUID parent specificato senza tipo di parent."

#: pypowervm/wrappers/entry_wrapper.py:1004
msgid "The search() method requires exactly one key=value argument."
msgstr "Il metodo search() richiede un solo argomento key=value."

#: pypowervm/wrappers/entry_wrapper.py:1035
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "La classe wrapper %(class)s non supporta la chiave di ricerca '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:1136
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using"
" it will result in a no-op.  At worst, it will give you incurable etag "
"mismatch errors."
msgstr ""
"Il parametro 'xag' per EntryWrapper.update è obsoleto.  Nel migliore dei casi, il suo utilizzo"
" non produrrà alcuna operazione.  Nel peggiore dei casi, produrrà degli errori di mancata corrispondenza "
"di etag incorreggibili."

#: pypowervm/wrappers/entry_wrapper.py:1406
msgid "No such child element."
msgstr "Nessun elemento child di questo genere."

#: pypowervm/wrappers/entry_wrapper.py:1467
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Impossibile impostare l'UUID sul wrapper senza metadati."

#: pypowervm/wrappers/entry_wrapper.py:1472
#, python-format
msgid "uuid value not valid: %s"
msgstr "Il valore uuid non è valido: %s"

#: pypowervm/wrappers/entry_wrapper.py:1527
msgid "Must specify a Wrapper subclass."
msgstr "È necessario specificare una sottoclasse wrapper."

#: pypowervm/wrappers/entry_wrapper.py:1536
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "È necessario specificare sia la classe parent che l'UUID parent, o nessuno dei due."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "Monitoraggio lavoro %(job_id)s per %(time)i secondi."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely"
" for termination."
msgstr ""
"Emettere una richiesta di annullamento per il lavoro %(job_id)s. Verrà eseguito il polling del lavoro indefinitamente"
" per terminarlo."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Lavoro %s non eliminato. Il lavoro è in stato In esecuzione."

#: pypowervm/wrappers/logical_partition.py:169
msgid "LPAR is not in an active state."
msgstr "La LPAR non è in stato Attivo."

#: pypowervm/wrappers/logical_partition.py:179
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "Il sistema di destinazione non ha la capacità LPAR Mobility IBM i."

#: pypowervm/wrappers/logical_partition.py:183
msgid "IBM i LPAR does not have restricted I/O."
msgstr "La LPAR IBM i non ha I/O limitato."

#: pypowervm/wrappers/logical_partition.py:186
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Il sistema di origine non ha la capacità LPAR Mobility IBM i."

#: pypowervm/wrappers/logical_partition.py:190
msgid "LPAR does not have an active RMC connection."
msgstr "La LPAR non ha una connessione RMC attiva."

#: pypowervm/wrappers/logical_partition.py:193
msgid "LPAR is the management partition"
msgstr "LPAR è la partizione di gestione"

#: pypowervm/wrappers/logical_partition.py:197
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "La LPAR non è disponibile per LPM a causa di capacità DLPAR mancanti."

#: pypowervm/wrappers/logical_partition.py:214
#: pypowervm/wrappers/logical_partition.py:223
#: pypowervm/wrappers/logical_partition.py:231
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a "
"NovaLink environment."
msgstr ""
"Questa non è la proprietà che si sta cercando.  Utilizzare srr_enabled in un "
"ambiente NovaLink."

#: pypowervm/wrappers/logical_partition.py:267
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc non valido '%s'."

#: pypowervm/wrappers/managed_system.py:506
msgid "This property is deprecated! Use pci_subsys_dev_id instead."
msgstr "Questa proprietà è obsoleta. Utilizzare invece pci_subsys_dev_id."

#: pypowervm/wrappers/managed_system.py:518
msgid "This property is deprecated! Use pci_rev_id instead."
msgstr "Questa proprietà è obsoleta. Utilizzare invece pci_rev_id."

#: pypowervm/wrappers/managed_system.py:534
msgid "This property is deprecated! Use pci_subsys_vendor_id instead."
msgstr "Questa proprietà è obsoleta. Utilizzare invece pci_subsys_vendor_id."

#: pypowervm/wrappers/managed_system.py:546
msgid "This property is deprecated! Use drc_index instead."
msgstr "Questa proprietà è obsoleta. Utilizzare invece drc_index."

#: pypowervm/wrappers/managed_system.py:558
msgid "This property is deprecated! Use drc_name instead."
msgstr "Questa proprietà è obsoleta. Utilizzare invece drc_name."

#: pypowervm/wrappers/network.py:1160
msgid "Invalid parent spec for CNA.create."
msgstr "Specifica parent non valido per CNA.create."

#: pypowervm/wrappers/storage.py:886
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV aveva un descrittore pg83 codificato \"%(pg83_raw)s\", ma non è riuscito a decodificare "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please"
" use values from pypowervm.const.XAG instead."
msgstr ""
"La proprietà 'xags' della classe VIOS EntryWrapper è obsoleta!  Utilizzare"
" invece i valori ricavati da pypowervm.const.XAG."

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr "La partizione di tipo VIOS non supporta LPM"

#: pypowervm/wrappers/virtual_io_server.py:670
msgid "Can't specify target device LUA without a backing storage device!"
msgstr "Impossibile specificare la LUA di dispositivo di destinazione senza un dispositivo di memoria di supporto."


# ENGL1SH_VERS10N 29539_40 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG VC142AAP001 2
