# Translations template for pypowervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the pypowervm project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.1.11.dev47\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-10-02 09:44-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: pypowervm/adapter.py:122
#, python-format
msgid "Invalid protocol \"%s\""
msgstr ""

#: pypowervm/adapter.py:128
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr ""

#: pypowervm/adapter.py:142
msgid "Calculating default audit memento failed, using 'default'."
msgstr ""

#: pypowervm/adapter.py:183
msgid "Local authentication not supported on HMC."
msgstr ""

#: pypowervm/adapter.py:202
#, python-format
msgid "Setting up event listener for %s"
msgstr ""

#: pypowervm/adapter.py:272
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr ""

#: pypowervm/adapter.py:316
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr ""

#: pypowervm/adapter.py:318
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr ""

#: pypowervm/adapter.py:355
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer "
"be used."
msgstr ""

#: pypowervm/adapter.py:363
#, python-format
msgid "Attempting re-login %s"
msgstr ""

#: pypowervm/adapter.py:374
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""

#: pypowervm/adapter.py:379
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""

#: pypowervm/adapter.py:383
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""

#: pypowervm/adapter.py:401
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""

#: pypowervm/adapter.py:404
#, python-format
msgid "suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr ""

#: pypowervm/adapter.py:456
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""

#: pypowervm/adapter.py:463
#, python-format
msgid "Session logging on %s"
msgstr ""

#: pypowervm/adapter.py:526
msgid "Failed to parse a session token from the PowerVM response."
msgstr ""

#: pypowervm/adapter.py:528 pypowervm/adapter.py:544
#, python-format
msgid " Body= %s"
msgstr ""

#: pypowervm/adapter.py:542
msgid "Failed to parse a session file path from the PowerVM response."
msgstr ""

#: pypowervm/adapter.py:556
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr ""

#: pypowervm/adapter.py:566
#, python-format
msgid "Session logging off %s"
msgstr ""

#: pypowervm/adapter.py:571
msgid "Problem logging off.  Ignoring."
msgstr ""

#: pypowervm/adapter.py:673
msgid "job must be a JobRequest element"
msgstr ""

#: pypowervm/adapter.py:677
msgid "JobRequest is missing OperationName"
msgstr ""

#: pypowervm/adapter.py:691 pypowervm/adapter.py:847 pypowervm/adapter.py:900
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr ""

#: pypowervm/adapter.py:809
#, python-format
msgid "path=%s not a PowerVM API reference"
msgstr ""

#: pypowervm/adapter.py:915 pypowervm/adapter.py:932
msgid "Invalid file descriptor"
msgstr ""

#: pypowervm/adapter.py:1018 pypowervm/adapter.py:1046
#: pypowervm/adapter.py:1061
msgid "Expected root_id"
msgstr ""

#: pypowervm/adapter.py:1020
msgid "Expected child_type"
msgstr ""

#: pypowervm/adapter.py:1024 pypowervm/adapter.py:1050
#: pypowervm/adapter.py:1055
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr ""

#: pypowervm/adapter.py:1027 pypowervm/adapter.py:1058
msgid "Expected suffix_parm"
msgstr ""

#: pypowervm/adapter.py:1029 pypowervm/adapter.py:1048
#: pypowervm/adapter.py:1063
msgid "Expected child_id"
msgstr ""

#: pypowervm/adapter.py:1032 pypowervm/adapter.py:1041
msgid "Unexpected child_id"
msgstr ""

#: pypowervm/adapter.py:1034 pypowervm/adapter.py:1043
msgid "Unexpected root_id"
msgstr ""

#: pypowervm/adapter.py:1065
#, python-format
msgid "Unexpected req_method=%s"
msgstr ""

#: pypowervm/adapter.py:1133
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr ""

#: pypowervm/adapter.py:1146
msgid "Response is not an Atom feed/entry"
msgstr ""

#: pypowervm/adapter.py:1157
msgid "Unexpected HTTP 204 for request"
msgstr ""

#: pypowervm/adapter.py:1165
msgid "Unexpectedly empty response body"
msgstr ""

#: pypowervm/adapter.py:1168
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""

#: pypowervm/adapter.py:1176
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr ""

#: pypowervm/adapter.py:1217
msgid "Session must not be None"
msgstr ""

#: pypowervm/adapter.py:1219
msgid "An event listener is already active on the session."
msgstr ""

#: pypowervm/adapter.py:1238
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr ""

#: pypowervm/adapter.py:1242
#, python-format
msgid "Application id \"%s\" not unique"
msgstr ""

#: pypowervm/adapter.py:1250
msgid "Shutting down"
msgstr ""

#: pypowervm/adapter.py:1253
msgid "This handler is already subscribed"
msgstr ""

#: pypowervm/adapter.py:1261
msgid "Handler must be an EventHandler"
msgstr ""

#: pypowervm/adapter.py:1264
msgid "Handler not found in subscriber list"
msgstr ""

#: pypowervm/adapter.py:1271
#, python-format
msgid "Shutting down EventListener for %s"
msgstr ""

#: pypowervm/adapter.py:1275
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr ""

#: pypowervm/adapter.py:1295
#, python-format
msgid "Error while getting PowerVM events: %s.  (Is the pvm-rest service down?)"
msgstr ""

#: pypowervm/adapter.py:1338
#, python-format
msgid "Unexpected EventType=%s"
msgstr ""

#: pypowervm/adapter.py:1365
msgid "Error while processing PowerVM events"
msgstr ""

#: pypowervm/exceptions.py:127
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""

#: pypowervm/exceptions.py:133
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr ""

#: pypowervm/exceptions.py:137
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr ""

#: pypowervm/exceptions.py:141
msgid "Adapter not found"
msgstr ""

#: pypowervm/exceptions.py:145
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr ""

#: pypowervm/exceptions.py:149
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""

#: pypowervm/exceptions.py:154
#, python-format
msgid ""
"Can not perform OS shutdown on Virtual Machine %(lpar_nm)s because its "
"RMC connection is not active."
msgstr ""

#: pypowervm/exceptions.py:159
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr ""

#: pypowervm/exceptions.py:163
#, python-format
msgid ""
"Power off of Virtual Machine %(lpar_nm)s timed out after %(timeout)d "
"seconds."
msgstr ""

#: pypowervm/exceptions.py:168
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr ""

#: pypowervm/exceptions.py:172
#, python-format
msgid ""
"Power on of Virtual Machine %(lpar_nm)s timed out after %(timeout)d "
"seconds."
msgstr ""

#: pypowervm/exceptions.py:177
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""

#: pypowervm/exceptions.py:182
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""

#: pypowervm/exceptions.py:191
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""

#: pypowervm/exceptions.py:196
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""

#: pypowervm/exceptions.py:203
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""

#: pypowervm/exceptions.py:210
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr ""

#: pypowervm/exceptions.py:214
msgid "FeedTask can't have an empty feed."
msgstr ""

#: pypowervm/exceptions.py:218
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr ""

#: pypowervm/exceptions.py:222
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""

#: pypowervm/exceptions.py:227
#, python-format
msgid "The migration task failed. %(error)s"
msgstr ""

#: pypowervm/exceptions.py:231
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr ""

#: pypowervm/exceptions.py:235
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The "
"parent_entry attribute is not set.  This may be due to using a PV "
"obtained through an unsupported property chain.  The PV must be accessed "
"via VIOS.phys_vols, VG.phys_vols, or "
"VIOS.scsi_mappings[n].backing_storage."
msgstr ""

#: pypowervm/exceptions.py:243
#, python-format
msgid ""
"Unable to remap storage element of vSCSI mapping. Expected to find "
"exactly one matching mapping, found %(num_mappings)d."
msgstr ""

#: pypowervm/exceptions.py:249
#, python-format
msgid ""
"Unable to remap storage element of vSCSI mapping. A mapping for storage "
"element %(stg_name)s already exists to client LPAR %(lpar_uuid)s."
msgstr ""

#: pypowervm/exceptions.py:255
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most "
"once."
msgstr ""

#: pypowervm/exceptions.py:270
#, python-format
msgid ""
"FeedTask %(ft_name)s experienced multiple exceptions:\n"
"\t%(concat_msgs)s"
msgstr ""

#: pypowervm/exceptions.py:280
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr ""

#: pypowervm/exceptions.py:286
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found "
"%(count)d."
msgstr ""

#: pypowervm/exceptions.py:292
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr ""

#: pypowervm/exceptions.py:301
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""

#: pypowervm/exceptions.py:306
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's"
" device with UDID %(udid)s."
msgstr ""

#: pypowervm/exceptions.py:311
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual "
"I/O Servers."
msgstr ""

#: pypowervm/exceptions.py:316
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of "
"%(io_type)s which is not supported for VM rebuild."
msgstr ""

#: pypowervm/exceptions.py:321
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not"
" match the number of slots on the client system (%(original_slots)d).  "
"Unable to rebuild this virtual machine on this system."
msgstr ""

#: pypowervm/exceptions.py:328
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC "
"adapter is needed. Instead the following was given: %(wrapper)s."
msgstr ""

#: pypowervm/exceptions.py:334
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected "
"%(exp)d; found %(act)d."
msgstr ""

#: pypowervm/exceptions.py:339
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC "
"connectivity between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""

#: pypowervm/exceptions.py:349
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""

#: pypowervm/exceptions.py:354
#, python-format
msgid ""
"Unable to fulfill redundancy requirement of %(red)d.  Found %(found_vfs)d"
" viable backing device(s)."
msgstr ""

#: pypowervm/exceptions.py:359
msgid "The Managed System is not vNIC capable."
msgstr ""

#: pypowervm/exceptions.py:363
msgid "There are no active vNIC-capable VIOSes."
msgstr ""

#: pypowervm/exceptions.py:367
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but the Managed System is not vNIC"
" failover capable."
msgstr ""

#: pypowervm/exceptions.py:372
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but there are no active vNIC "
"failover-capable VIOSes."
msgstr ""

#: pypowervm/exceptions.py:377
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""

#: pypowervm/exceptions.py:383
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested"
" to one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""

#: pypowervm/exceptions.py:389
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr ""

#: pypowervm/exceptions.py:393
msgid "The Adapter cache is not supported."
msgstr ""

#: pypowervm/exceptions.py:397
#, python-format
msgid ""
"Invalid value '%(value)s' for '%(enum)s'.  Valid values are: "
"%(valid_values)s"
msgstr ""

#: pypowervm/exceptions.py:402
#, python-format
msgid "No VIOS found with name %(vios_name)s."
msgstr ""

#: pypowervm/exceptions.py:406
#, python-format
msgid "No volume group found with name %(vg_name)s."
msgstr ""

#: pypowervm/exceptions.py:410
#, python-format
msgid "Partition with name %(part_name)s is not an IBMi partition."
msgstr ""

#: pypowervm/exceptions.py:414
msgid "PanelJob function partition argument is empty."
msgstr ""

#: pypowervm/exceptions.py:418
#, python-format
msgid ""
"Panel function operation %(op_name)s is invalid. One of %(valid_ops)s "
"expected."
msgstr ""

#: pypowervm/exceptions.py:423
#, python-format
msgid "ISCSI discovery failed for VIOS %(vios_uuid)s. Return code: %(status)s"
msgstr ""

#: pypowervm/exceptions.py:429
#, python-format
msgid "ISCSI Logout failed for VIOS %(vios_uuid)s. Return code: %(status)s"
msgstr ""

#: pypowervm/exceptions.py:434
#, python-format
msgid "ISCSI Remove failed for VIOS %(vios_uuid)s. Return code: %(status)s"
msgstr ""

#: pypowervm/exceptions.py:439
#, python-format
msgid "Vstor %(stor_udid)s not found for VIOS %(vios_uuid)s."
msgstr ""

#: pypowervm/util.py:125
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""

#: pypowervm/util.py:221
msgid "Certificate has expired."
msgstr ""

#: pypowervm/util.py:371
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr ""

#: pypowervm/util.py:376
msgid "Total length must be at least 1 character."
msgstr ""

#: pypowervm/util.py:399
msgid "The name parameter must be at least one character long."
msgstr ""

#: pypowervm/util.py:402
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr ""

#: pypowervm/util.py:500
msgid "Developer error: partial parent specification."
msgstr ""

#: pypowervm/util.py:505
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""

#: pypowervm/util.py:602
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr ""

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr ""

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:202
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:212
#, python-format
msgid "Creating marker LU %s"
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:228
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr ""

#: pypowervm/tasks/cluster_ssp.py:240
#, python-format
msgid "Removing failed LU %s."
msgstr ""

#: pypowervm/tasks/cna.py:119
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr ""

#: pypowervm/tasks/cna.py:143
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr ""

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""

#: pypowervm/tasks/partition.py:333
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did "
"not go active were: %(vioses)s."
msgstr ""

#: pypowervm/tasks/partition.py:376
#, python-format
msgid "Assuming description-less slot is physical I/O: %s"
msgstr ""

#: pypowervm/tasks/power.py:88
#, python-format
msgid "Partition %s already powered on."
msgstr ""

#: pypowervm/tasks/power.py:136
#, python-format
msgid "Partition %s already powered off."
msgstr ""

#: pypowervm/tasks/power.py:199
#, python-format
msgid ""
"Specifying add_parms as a dict is deprecated. Please specify a %s "
"instance instead."
msgstr ""

#: pypowervm/tasks/power.py:265
#, python-format
msgid ""
"IBMi OS normal shutdown failed.  Trying OS immediate shutdown.  "
"Partition: %s"
msgstr ""

#: pypowervm/tasks/power.py:275
#, python-format
msgid ""
"IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""

#: pypowervm/tasks/power.py:323
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown timed out.  Trying VSP hard shutdown.  "
"Partition: %s"
msgstr ""

#: pypowervm/tasks/power.py:327
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""

#: pypowervm/tasks/power.py:363
#, python-format
msgid "VSP hard shutdown with default timeout.  Partition: %s"
msgstr ""

#: pypowervm/tasks/scsi_mapper.py:39
msgid "Retrying modification of SCSI Mapping."
msgstr ""

#: pypowervm/tasks/scsi_mapper.py:99
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""

#: pypowervm/tasks/scsi_mapper.py:118
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""

#: pypowervm/tasks/scsi_mapper.py:489
msgid "Must not specify both match_func and stg_elem."
msgstr ""

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet "
"method."
msgstr ""

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr ""

#: pypowervm/tasks/sriov.py:398
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging"
" to LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: "
"%(vnic_uuid)s)."
msgstr ""

#: pypowervm/tasks/sriov.py:515
msgid ""
"Making changes to the following SR-IOV physical port labels even though "
"they are in use by vNICs:"
msgstr ""

#: pypowervm/tasks/storage.py:100
#, python-format
msgid "Failed to delete vio_file with UUID %s.  It must be manually deleted."
msgstr ""

#: pypowervm/tasks/storage.py:356
msgid "Encountered an issue while uploading. Will retry."
msgstr ""

#: pypowervm/tasks/storage.py:530
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu "
"method (clone=src_lu, size=lu_size_gb)."
msgstr ""

#: pypowervm/tasks/storage.py:581
#, python-format
msgid "Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr ""

#: pypowervm/tasks/storage.py:665
msgid "Unable to locate new vDisk on file upload."
msgstr ""

#: pypowervm/tasks/storage.py:752
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""

#: pypowervm/tasks/storage.py:758
#, python-format
msgid "Device %s not found in list."
msgstr ""

#: pypowervm/tasks/storage.py:787
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr ""

#: pypowervm/tasks/storage.py:810
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr ""

#: pypowervm/tasks/storage.py:866
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr ""

#: pypowervm/tasks/storage.py:870
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""

#: pypowervm/tasks/storage.py:888
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""

#: pypowervm/tasks/storage.py:893
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr ""

#: pypowervm/tasks/storage.py:919
msgid "Developer error: Either tier or lufeed is required."
msgstr ""

#: pypowervm/tasks/storage.py:924
msgid "Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr ""

#: pypowervm/tasks/storage.py:931
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr ""

#: pypowervm/tasks/storage.py:936
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band."
"  (UDID: %(lu_udid)s)"
msgstr ""

#: pypowervm/tasks/storage.py:992
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""

#: pypowervm/tasks/storage.py:1018
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr ""

#: pypowervm/tasks/storage.py:1045
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""

#: pypowervm/tasks/storage.py:1112
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot "
"be determined whether it is still in use.  Manual verification and "
"cleanup may be necessary."
msgstr ""

#: pypowervm/tasks/storage.py:1123
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""

#: pypowervm/tasks/storage.py:1141
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""

#: pypowervm/tasks/storage.py:1149
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""

#: pypowervm/tasks/storage.py:1220
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""

#: pypowervm/tasks/vfc_mapper.py:543
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""

#: pypowervm/tasks/vfc_mapper.py:572
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to "
"mapping for client wwpns: %(wwpns)s"
msgstr ""

#: pypowervm/tasks/vopt.py:75
msgid ""
"An error occurred querying the virtual optical media repository.  "
"Attempting to re-establish connection with a virtual optical media "
"repository."
msgstr ""

#: pypowervm/tasks/vterm.py:86
msgid "Unable to close vterm."
msgstr ""

#: pypowervm/tasks/vterm.py:138
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr ""

#: pypowervm/tasks/vterm.py:351
#, python-format
msgid "VNCSocket Listener Listening on ip=%(ip)s port=%(port)s"
msgstr ""

#: pypowervm/tasks/vterm.py:480
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid "QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr ""

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:64
msgid "ISCSI command completed successfully"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:66
msgid "ISCSI session already exists and logged in"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:68
msgid "ISCSI command performed on unsupported VIOS, host."
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:71
msgid "ISCSI discovery found stale entries in the ODM database."
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:74
msgid "ISCSI session could not be found "
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:76
msgid "No records/targets/sessions/portals found to execute operation on"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:79
#, python-format
msgid "ISCSI command failed with internal error status = %s"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:82
msgid "ISCSI generic error code"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:84
msgid "ISCSI session login failure"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:86
msgid "ISCSI command invalid arguments"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:88
msgid "ISCSI connection timer exired while trying to connect."
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:90
msgid "ISCSI command could not lookup host"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:92
#, python-format
msgid "ISCSI command returned unexpected status = %s"
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:151
msgid "ISCSI command performed on unsupported VIOS "
msgstr ""

#: pypowervm/tasks/hdisk/_iscsi.py:287
#, python-format
msgid "Scrub stale storage for LPAR IDs %s and retry iSCSI discovery."
msgstr ""

#: pypowervm/tasks/monitor/util.py:452
msgid ""
"Metric data is not available.  This may be due to the metrics being "
"recently initialized."
msgstr ""

#: pypowervm/tests/test_i18n.py:34
msgid "This is a test"
msgstr ""

#: pypowervm/tests/test_i18n.py:37
msgid "This is a message for which a translation doesn't exist"
msgstr ""

#: pypowervm/utils/lpar_builder.py:216
#, python-format
msgid "Processor units factor must be between 0.05 and 1.0. Value: %s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:244
#, python-format
msgid "Logical partition name has invalid length. Name: %s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:448
#, python-format
msgid "Field '%(field)s' has invalid value: '%(value)s'"
msgstr ""

#: pypowervm/utils/lpar_builder.py:503
msgid "None value is not valid."
msgstr ""

#: pypowervm/utils/lpar_builder.py:510
#, python-format
msgid ""
"Value '%(value)s' is not valid for field '%(field)s' with acceptable "
"choices: %(choices)s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:535
#, python-format
msgid ""
"Field '%(field)s' has a value below the minimum. Value: %(value)s; "
"Minimum: %(minimum)s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:544
#, python-format
msgid ""
"Field '%(field)s' has a value above the maximum. Value: %(value)s; "
"Maximum: %(maximum)s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:598
#, python-format
msgid ""
"The '%(desired_field)s' has a value above the '%(max_field)s' value. "
"Desired: %(desired)s Maximum: %(maximum)s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:611
#, python-format
msgid ""
"The '%(desired_field)s' has a value below the '%(min_field)s' value. "
"Desired: %(desired)s Minimum: %(minimum)s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:655
#, python-format
msgid ""
"Memory value is not a multiple of the logical memory block size "
"(%(lmb_size)s) of  the host.  Value: %(value)s"
msgstr ""

#: pypowervm/utils/lpar_builder.py:666
#, python-format
msgid ""
"The managed system does not support active memory expansion. The "
"expansion factor value '%(value)s' is not valid."
msgstr ""

#: pypowervm/utils/lpar_builder.py:672
#, python-format
msgid ""
"Active memory expansion value must be greater than or equal to 1.0 and "
"less than or equal to 10.0. A value of 0 is also valid and indicates that"
" AME is off. '%(value)s' is not valid."
msgstr ""

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr ""

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr ""

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr ""

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr ""

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr ""

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr ""

#: pypowervm/utils/transaction.py:789
#, python-format
msgid ""
"FeedTask %s experienced multiple exceptions. They are logged individually"
" below."
msgstr ""

#: pypowervm/utils/validation.py:174
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""

#: pypowervm/utils/validation.py:209
msgid "memory"
msgstr ""

#: pypowervm/utils/validation.py:230
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/utils/validation.py:235
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/utils/validation.py:328
msgid "CPUs"
msgstr ""

#: pypowervm/utils/validation.py:344
msgid "processing units"
msgstr ""

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/utils/validation.py:395
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/utils/validation.py:411
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/utils/validation.py:419
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/utils/validation.py:448
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""

#: pypowervm/utils/validation.py:460
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""

#: pypowervm/utils/validation.py:533
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""

#: pypowervm/wrappers/base_partition.py:434
msgid "Partition does not have an active RMC connection."
msgstr ""

#: pypowervm/wrappers/base_partition.py:437
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr ""

#: pypowervm/wrappers/base_partition.py:449
msgid "I/O"
msgstr ""

#: pypowervm/wrappers/base_partition.py:459
msgid "Memory"
msgstr ""

#: pypowervm/wrappers/base_partition.py:469
msgid "Processors"
msgstr ""

#: pypowervm/wrappers/base_partition.py:649
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr ""

#: pypowervm/wrappers/base_partition.py:660
#, python-format
msgid "Invalid BootMode '%s'."
msgstr ""

#: pypowervm/wrappers/base_partition.py:1501
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr ""

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the"
" master console for the pool."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:635
msgid "Refusing to construct and wrap an Element without a tag."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:760
msgid "Response is missing 'entry' property."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:774
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:861
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to"
" retrieve a CHILD object."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:866
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:879
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD "
"feed or entry."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:882
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:886
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1001
msgid "Parent UUID specified without parent type."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1004
msgid "The search() method requires exactly one key=value argument."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1035
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1136
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using"
" it will result in a no-op.  At worst, it will give you incurable etag "
"mismatch errors."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1406
msgid "No such child element."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1467
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1472
#, python-format
msgid "uuid value not valid: %s"
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1527
msgid "Must specify a Wrapper subclass."
msgstr ""

#: pypowervm/wrappers/entry_wrapper.py:1536
msgid "Must specify both parent class and parent UUID, or neither."
msgstr ""

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr ""

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely"
" for termination."
msgstr ""

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:169
msgid "LPAR is not in an active state."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:179
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:183
msgid "IBM i LPAR does not have restricted I/O."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:186
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:190
msgid "LPAR does not have an active RMC connection."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:193
msgid "LPAR is the management partition"
msgstr ""

#: pypowervm/wrappers/logical_partition.py:197
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:214
#: pypowervm/wrappers/logical_partition.py:223
#: pypowervm/wrappers/logical_partition.py:231
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a "
"NovaLink environment."
msgstr ""

#: pypowervm/wrappers/logical_partition.py:267
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr ""

#: pypowervm/wrappers/managed_system.py:506
msgid "This property is deprecated! Use pci_subsys_dev_id instead."
msgstr ""

#: pypowervm/wrappers/managed_system.py:518
msgid "This property is deprecated! Use pci_rev_id instead."
msgstr ""

#: pypowervm/wrappers/managed_system.py:534
msgid "This property is deprecated! Use pci_subsys_vendor_id instead."
msgstr ""

#: pypowervm/wrappers/managed_system.py:546
msgid "This property is deprecated! Use drc_index instead."
msgstr ""

#: pypowervm/wrappers/managed_system.py:558
msgid "This property is deprecated! Use drc_name instead."
msgstr ""

#: pypowervm/wrappers/network.py:1160
msgid "Invalid parent spec for CNA.create."
msgstr ""

#: pypowervm/wrappers/storage.py:886
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please"
" use values from pypowervm.const.XAG instead."
msgstr ""

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr ""

#: pypowervm/wrappers/virtual_io_server.py:670
msgid "Can't specify target device LUA without a backing storage device!"
msgstr ""

